slug: state_of_react_native
hashtag: StateOfReactNative
domain: stateofreactnative.com
name: State of React Native

emailOctopus:
  listId: 9733c8c9-4c8c-4b4b-b08d-0d287271098b

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/nijibox.svg
