surveyId: js2020
id: js2020
startedAt: December 1, 2020
endedAt: January 1, 2021
# questionsUrl: https://survey.devographics.com/survey/state-of-js/2020
resultsUrl: https://2020.stateofjs.com/
year: 2020
status: 3 # closed
resultsStatus: 3 # hidden/preview/published
imageUrl: https://static.devographics.com/stateofjs/2020/images/stateofjs2020.png

colors:
  background: "#212424"
  primary: "#41c7c7"
  secondary: "#FE6A6A"
  text: "#e1e1e1"

tags:
  - js
