id: css2020 # used as first part of field names
surveyId: css2020 # used as first part of field names
startedAt: October 1, 2020
endedAt: November 1, 2020
# questionsUrl: https://survey.devographics.com/survey/state-of-css/2020
resultsUrl: https://2020.stateofcss.com/
year: 2020
status: 3 # closed
resultsStatus: 3 # hidden/preview/published
imageUrl: https://static.devographics.com/stateofcss/2020/images/stateofcss2020.png

colors:
  background: "#232840"
  primary: "#f649a7"
  secondary: "#59df7f"
  text: "#9ac6c9"

tags:
  - css
