---
slug: rn2022
surveyId: rn2022
context: state_of_react_native
topic: JavaScript
createdAt: November 1, 2022
prettySlug: state-of-react-native
hashtag: StateOfJS
shareUrl: https://stateofjs.com
questionsUrl: https://survey.devographics.com/survey/state-of-js/2022
# resultsUrl: https://2022.stateofjs.com/
name: "State of JavaScript"
year: 2022
status: 2 # preview/open/closed/hidden
imageUrl: https://devographics.github.io/surveys/state_of_js/2022/images/js2022.png
faviconUrl: https://devographics.github.io/surveys/state_of_js/2022/images/js2022-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_js/2022/images/js2022-og.png
domain: stateofjs.com
bgColor: rgb(255, 255, 255)
textColor: rgb(224, 228, 228)
linkColor: rgb(65, 199, 199)
hoverColor: rgb(254, 106, 106)
tags: [rn]

colors: 
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(255, 255, 255)
  backgroundSecondary: rgb(48, 52, 53)
  